import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const styles = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8')
const icons = readFileSync(new URL('../src/UiIcon.vue', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/App.vue', import.meta.url), 'utf8')

function rule(selector) {
  const match = styles.match(new RegExp(`(?:^|\\n)${selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*\\{([^}]*)\\}`, 's'))
  assert.ok(match, `missing ${selector} rule`)
  return match[1]
}

test('keeps toolbar labels above contained, vertically centered actions', () => {
  assert.match(rule('.toolbar-group'), /grid-template-rows:\s*16px minmax\(0,\s*1fr\)/)
  assert.match(rule('.toolbar-actions'), /min-height:\s*0/)
  assert.match(rule('.toolbar-button'), /line-height:\s*1\.35/)
})

test('uses one outline-only SVG language for application icons', () => {
  assert.doesNotMatch(icons, /ui-icon-fill/)
  assert.doesNotMatch(icons, /<template[^>]*>[\s\S]*?\bfill=/)
  assert.match(icons, /stroke-width:\s*1\.75/)
})

test('uses readable workbench typography and shell rhythm', () => {
  assert.match(rule(':root'), /font-size:\s*14px/)
  assert.match(rule('button'), /min-height:\s*40px/)
  assert.match(rule('.command-toolbar'), /height:\s*72px/)
  assert.match(rule('.status-strip'), /height:\s*52px/)
  assert.match(rule('.app-footer'), /height:\s*34px/)
  assert.match(rule('.sidebar nav button'), /height:\s*50px/)
  assert.doesNotMatch(styles, /@media \(max-width:\s*1439px\)[\s\S]*?\.sidebar\s*\{\s*width:\s*56px/)
})

test('gives buttons distinct hover, pressed, focus, and disabled feedback', () => {
  assert.match(rule('button'), /transition:[^;}]*background-color[^;}]*box-shadow[^;}]*transform/)
  assert.match(rule('button:disabled'), /cursor:\s*not-allowed/)
  assert.match(rule('button:disabled'), /opacity:\s*1/)
  assert.match(rule('button.primary:hover:not(:disabled)'), /box-shadow:/)
  assert.match(rule('button.primary:active:not(:disabled), button.secondary:active:not(:disabled), button.danger:active:not(:disabled)'), /transform:\s*translateY\(1px\)/)
  assert.match(rule('button:focus-visible, input:focus-visible, select:focus-visible, textarea:focus-visible, summary:focus-visible'), /outline:\s*3px solid/)
  assert.match(rule('.sidebar nav button.active'), /box-shadow:\s*inset 3px 0 var\(--qt-primary\)/)
})

test('keeps readable object grouping, table density, and Chinese detail labels', () => {
  assert.match(rule(':root'), /--list-object-height:\s*48px/)
  assert.match(rule(':root'), /--list-subgroup-height:\s*44px/)
  assert.match(rule(':root'), /--list-leaf-height:\s*48px/)
  assert.match(rule('.interaction-object-group'), /height:\s*var\(--list-object-height\)/)
  assert.match(rule('.interaction-table-head'), /height:\s*42px/)
  assert.match(rule('.interaction-table-row'), /min-height:\s*var\(--list-leaf-height\)/)
  assert.match(rule('.target-cell strong'), /font-size:\s*14px/)
  assert.match(app, />接口详情</)
  assert.match(app, />断点编辑器</)
  assert.match(app, />调用详情</)
  assert.match(app, />会话详情</)
  assert.doesNotMatch(app, /INTERFACE DETAIL|STRUCTURED EDITOR|INTERACTION DETAIL|BROWSED SESSION/)
})

test('uses stable split workbenches and Object to Interface to Breakpoint grouping', () => {
  assert.match(rule('.content.split-content'), /overflow:\s*hidden/)
  assert.match(rule('.split-content > .session-layout'), /flex:\s*1 1 auto/)
  assert.match(rule('.split-content .session-list, .split-content .session-detail, .split-content .breakpoint-editor'), /overflow:\s*auto/)
  assert.match(app, /groupBreakpointsByInterface/)
  assert.match(app, /group\.interfaces/)
  assert.match(app, /class="object-group-header list-group-toggle breakpoint-object-header"[\s\S]*?:aria-expanded="!isListGroupCollapsed\('breakpoints', group\.object\)"/)
  assert.match(app, /class="breakpoint-interface-header list-group-toggle"[\s\S]*?:aria-expanded="!isBreakpointInterfaceCollapsed/)
  assert.match(app, /toggleListGroup\('breakpoints', group\.object\)/)
  assert.match(app, /toggleBreakpointInterface\(group\.object, interfaceGroup\.command\)/)
  assert.match(rule('.breakpoint-interface-header'), /height:\s*var\(--list-subgroup-height\)/)
  assert.match(rule('.breakpoint-list-head, .breakpoint-rule-row'), /grid-template-columns:\s*var\(--breakpoint-grid-columns\)/)
  assert.match(rule('.breakpoint-list-head, .breakpoint-rule-row'), /padding:\s*0 9px/)
  assert.doesNotMatch(rule('.breakpoint-rule-row'), /padding:/)
  assert.match(rule('.breakpoint-rule-name'), /padding-left:\s*34px/)
  assert.match(app, /breakpoint-rule-row/)
  assert.match(app, /interface-list-head/)
  assert.match(app, /interface-list-row/)
})

test('keeps call evidence readable inside the fixed detail pane', () => {
  assert.match(rule('.phase-cell'), /display:\s*grid/)
  assert.match(rule('.interaction-timeline ol'), /grid-template-columns:\s*minmax\(0,\s*1fr\)/)
  assert.match(rule('.interaction-drawer'), /min-height:\s*0/)
  assert.match(rule('.interaction-drawer'), /max-height:\s*100%/)
  assert.match(app, /const advancedFiltersOpen = ref\(false\)/)
  assert.match(app, /advancedFiltersOpen\.value\s*=\s*false/)
})

test('uses one keyboard entry per interaction row instead of one button per cell', () => {
  assert.match(app, /class="interaction-table-row"[\s\S]*?role="button"[\s\S]*?tabindex="0"/)
  assert.match(app, /@keydown\.enter\.prevent="openInteraction\(item\.interaction_id\)"/)
  assert.match(app, /@keydown\.space\.prevent="openInteraction\(item\.interaction_id\)"/)
  assert.match(app, /class="pause-selection-control" @click\.stop @keydown\.stop/)
  assert.doesNotMatch(app, /<button class="interaction-cell"/)
  assert.match(rule('.interaction-table-row:focus-visible'), /outline:\s*2px solid var\(--qt-primary\)/)
})

test('classifies call and session evidence behind fixed detail tabs', () => {
  assert.match(app, /const interactionDetailTab = ref\('overview'\)/)
  assert.match(app, /const sessionDetailTab = ref\('overview'\)/)
  assert.match(app, /总览[\s\S]*?Pause 审计[\s\S]*?Payload[\s\S]*?原始 JSON/)
  assert.match(app, /概览[\s\S]*?Breakpoint[\s\S]*?Interaction[\s\S]*?Pause[\s\S]*?原始归档/)
  assert.match(app, /v-if="browsedInteraction\.current_pause" class="injection-workbench"/)
  assert.match(rule('.detail-tab-shell'), /grid-template-rows:\s*auto 42px minmax\(0,\s*1fr\)/)
  assert.match(rule('.detail-tab-body'), /overflow:\s*auto/)
  assert.equal((app.match(/v-for="\(evidence, evidenceIndex\) in hitEvidenceRows\(snapshot\)"/g) || []).length, 2)
  assert.equal((app.match(/evidence\.operator\}-\$\{evidenceIndex\}/g) || []).length, 2)
})

test('uses a visible action header and balanced interaction overview', () => {
  assert.match(app, /class="panel-heading interaction-detail-heading"/)
  assert.match(app, /class="heading-actions interaction-detail-actions"/)
  assert.match(app, /class="drawer-close interaction-detail-close"[\s\S]*?<span>关闭<\/span>/)
  assert.match(app, /class="detail-list interaction-overview-summary"/)
  assert.match(app, /class="interaction-overview-grid"/)
  assert.match(rule('.interaction-workspace.detail-open'), /minmax\(600px,\s*1\.4fr\) minmax\(420px,\s*1fr\)/)
  assert.match(rule('.interaction-detail-heading'), /display:\s*grid/)
  assert.match(rule('.interaction-detail-heading'), /grid-template-columns:\s*minmax\(0,\s*1fr\) max-content/)
  assert.match(rule('.panel-heading > .interaction-detail-actions'), /display:\s*flex/)
  assert.match(rule('.interaction-overview-summary'), /grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/)
  assert.match(styles, /@container \(min-width:\s*600px\)[\s\S]*?\.interaction-overview-grid\s*\{\s*grid-template-columns:/)
})

test('keeps pause injection and continue actions visible and explicit', () => {
  assert.match(app, /class="primary compact interaction-continue-action"[\s\S]*?>继续执行<\/button>/)
  assert.match(app, /class="pause-injection-actions"/)
  assert.match(app, />应用修改（保持暂停）<\/button>/)
  assert.match(app, /先应用修改（仍保持暂停），确认后再继续；不修改可直接继续。/)
  assert.doesNotMatch(app, />注入但保持暂停<\/button>/)
  assert.match(rule('.pause-injection-actions'), /position:\s*sticky/)
  assert.match(rule('.pause-injection-actions'), /top:\s*0/)
})

test('applies one List System contract without forcing one page grid', () => {
  const groupTags = (app.match(/<button[\s\S]*?>/g) || []).filter(tag => tag.includes('list-group-toggle'))
  assert.equal(groupTags.length, 5)
  assert.equal(groupTags.every(tag => tag.includes(':aria-expanded=')), true)
  assert.equal(groupTags.every(tag => tag.includes('@keydown.enter.prevent=') && tag.includes('@keydown.space.prevent=')), true)
  assert.doesNotMatch(app, /<div[^>]*class="[^"]*(?:object-group-header|interaction-object-group)/)
  assert.match(rule('.list-group-toggle'), /width:\s*100%/)
  assert.match(rule('.list-group-toggle'), /cursor:\s*pointer/)
  assert.match(rule('.list-group-toggle:focus-visible'), /outline:\s*2px solid var\(--qt-primary\)/)

  assert.match(app, /class="interaction-filters list-toolbar"/)
  assert.match(app, /class="interaction-selection-toolbar list-toolbar list-toolbar-selection"/)
  assert.match(app, /class="session-filters panel list-toolbar"/)
  assert.match(styles, /\.list-toolbar input,[\s\S]*?\.list-toolbar button\s*\{\s*height:\s*40px;\s*min-height:\s*40px/)
  assert.match(rule('.interaction-selection-toolbar'), /justify-content:\s*space-between/)
  assert.match(rule('.interaction-selection-toolbar .list-toolbar-action'), /height:\s*34px/)
  assert.match(rule('.interaction-selection-toolbar .list-toolbar-action'), /min-height:\s*34px/)

  assert.match(rule('.interface-list-head, .interface-list-row'), /minmax\(140px,\s*1fr\)[\s\S]*50px[\s\S]*64px[\s\S]*116px/)
  assert.match(app, /class="interface-summary-inline"/)
  assert.match(styles, /@media \(min-width:\s*1600px\)[\s\S]*?\.interface-list-head, \.interface-list-row\s*\{[\s\S]*?minmax\(190px,\s*240px\)[\s\S]*?minmax\(180px,\s*1fr\)/)
  assert.match(rule('.observation-layout'), /grid-template-columns:\s*minmax\(620px,\s*60%\) minmax\(400px,\s*1fr\)/)
  assert.match(rule('.breakpoint-layout'), /--breakpoint-grid-columns:\s*64px minmax\(160px,\s*240px\)[\s\S]*minmax\(120px,\s*1fr\)/)
  assert.match(styles, /@media \(min-width:\s*1600px\)[\s\S]*?\.breakpoint-layout\s*\{[^}]*grid-template-columns:\s*minmax\(650px,\s*40%\) minmax\(680px,\s*1fr\)/)
  assert.match(rule('.interaction-table-head, .interaction-table-row'), /32px 92px minmax\(170px,\s*1fr\)[\s\S]*44px 44px/)
  assert.match(styles, /@media \(min-width:\s*1180px\) and \(max-width:\s*1599px\)[\s\S]*?\.interaction-workspace:not\(\.detail-open\)[\s\S]*?minmax\(190px,\s*320px\)[\s\S]*?minmax\(180px,\s*1fr\)/)
  assert.match(app, /class="interaction-cell evidence-cell"/)
  assert.match(app, /class="interaction-cell evidence-subcell rule-evidence"/)
  assert.match(app, /class="interaction-cell evidence-subcell result-evidence"/)
  assert.match(app, /class="interaction-cell evidence-subcell payload-evidence"/)
  assert.match(app, /class="target-evidence-inline"/)
  assert.match(styles, /@media \(min-width:\s*1600px\)[\s\S]*?\.evidence-rule-head[\s\S]*?\.evidence-result-head[\s\S]*?\.evidence-payload-head[\s\S]*?display:\s*flex/)
  assert.match(app, /class="interaction-group-summary"/)

  assert.match(styles, /@media \(max-width:\s*1179px\)[\s\S]*?\.breakpoint-layout\s*\{\s*--breakpoint-grid-columns:\s*58px minmax\(150px,\s*1fr\) 72px/)
  assert.match(styles, /@media \(min-width:\s*1180px\) and \(max-width:\s*1599px\)[\s\S]*?\.breakpoint-layout\s*\{[^}]*grid-template-columns:\s*minmax\(320px,\s*34%\) minmax\(560px,\s*1fr\)/)
  assert.match(styles, /@media \(max-width:\s*1179px\)[\s\S]*?\.observation-layout \.interface-list-head,[\s\S]*?grid-template-columns:\s*minmax\(110px,\s*1fr\) 96px/)

  assert.match(rule('.session-list .session-row'), /min-height:\s*58px/)
  assert.match(rule('.session-list .session-row small'), /min-height:\s*17px/)
  assert.match(rule('.session-list .session-row small'), /line-height:\s*17px/)
  assert.match(rule('.overview-event-row'), /height:\s*var\(--list-leaf-height\)/)
  assert.match(styles, /\.overview-event-row,[\s\S]*?\.session-row\s*\{\s*outline:\s*none/)
  assert.match(styles, /\.overview-event-row:focus-visible,[\s\S]*?\.session-row:focus-visible\s*\{[\s\S]*?outline-offset:\s*-2px/)
})

test('contains filter controls and uses wide space for real evidence', () => {
  assert.match(app, /class="interaction-filters list-toolbar"\s*:class="\{ 'advanced-open': advancedFiltersOpen \}"/)
  assert.match(app, /class="advanced-filter-toggle"[\s\S]*?:aria-expanded="advancedFiltersOpen"/)
  assert.match(app, /class="advanced-filter-fields"/)
  assert.match(rule('.interaction-filters'), /height:\s*82px/)
  assert.match(rule('.interaction-filters'), /flex:\s*0 0 82px/)
  assert.match(rule('.interaction-filters.advanced-open'), /height:\s*158px/)
  assert.match(rule('.interaction-filters.advanced-open'), /flex-basis:\s*158px/)
  assert.doesNotMatch(rule('.advanced-filter-fields'), /position:\s*absolute/)

  assert.equal((app.match(/class="list-group-summary"/g) || []).length, 4)
  assert.match(rule('.object-group-header'), /justify-content:\s*flex-start/)
  assert.match(rule('.breakpoint-interface-header'), /justify-content:\s*flex-start/)
  assert.match(rule('.list-group-summary > span'), /border-left:/)
  assert.match(rule('.list-group-summary > span'), /padding:\s*0 9px/)
  assert.doesNotMatch(rule('.list-group-summary > span'), /padding-left:/)
  assert.match(rule('.interaction-group-summary'), /gap:\s*0 !important/)
  assert.match(rule('.interaction-group-summary > strong'), /margin-right:\s*9px/)
  assert.match(rule('.interaction-group-summary > span'), /padding:\s*0 9px/)
  assert.doesNotMatch(rule('.interaction-group-summary > span'), /padding-left:/)

  assert.match(app, /class="overview-wide-evidence overview-duration"/)
  assert.match(app, /class="overview-wide-evidence overview-result"/)
  assert.match(app, /class="interface-wide-evidence interface-recent-state"/)
  assert.match(app, /class="interface-wide-evidence interface-recent-duration"/)
  assert.match(styles, /@media \(min-width:\s*1600px\)[\s\S]*?\.overview-table-head, \.overview-event-row\s*\{[\s\S]*?grid-template-columns:[^;}]*minmax\(160px,\s*1fr\)/)
  assert.match(styles, /@media \(min-width:\s*1600px\)[\s\S]*?\.observation-layout\s*\{\s*grid-template-columns:\s*minmax\(760px,\s*920px\)/)
  assert.match(app, /new Date\(item\.before_at \|\| 0\)\.getTime\(\) > new Date\(current\.before_at \|\| 0\)\.getTime\(\)/)
  assert.match(app, /function latestInterfaceInteraction\(item\)/)

  assert.match(app, /class="detail-list session-overview-list"/)
  assert.match(app, /class="condition-editor-pane"/)
  assert.match(styles, /@media \(min-width:\s*1600px\)[\s\S]*?\.session-overview-list\s*\{[\s\S]*?grid-template-columns:\s*repeat\(2,/)
  assert.match(styles, /@container \(min-width:\s*900px\)[\s\S]*?\.breakpoint-draft-workspace\s*\{[\s\S]*?grid-template-columns:[\s\S]*?align-items:\s*stretch/)
  assert.match(rule('.condition-target-grid'), /grid-template-columns:\s*minmax\(160px,\s*\.68fr\) minmax\(240px,\s*1\.32fr\)/)
  assert.match(rule('.condition-value-row'), /grid-template-columns:\s*110px minmax\(0,\s*1fr\)/)
  assert.match(rule('.condition-preview'), /flex:\s*1 1 auto/)
})

test('breakpoint suggestions wrap without horizontal scrolling and scrollbars stay unobtrusive', () => {
  assert.match(app, /class="session-layout breakpoint-layout"\s*:class="\{ 'breakpoint-layout-empty': !breakpoints\.length \}"/)
  assert.match(rule('.split-content .breakpoint-layout > .session-list'), /height:\s*auto/)
  assert.match(rule('.split-content .breakpoint-layout > .session-list'), /max-height:\s*100%/)
  assert.match(rule('.split-content .breakpoint-layout > .session-list'), /overflow-x:\s*hidden/)
  assert.match(rule('.breakpoint-layout.breakpoint-layout-empty'), /grid-template-columns:\s*minmax\(0,\s*1fr\)/)
  assert.match(rule('.breakpoint-layout-empty > .session-list'), /height:\s*auto/)
  assert.match(rule('.breakpoint-target-suggestions > div > span'), /display:\s*grid/)
  assert.match(rule('.breakpoint-target-suggestions > div'), /grid-template-columns:\s*minmax\(0,\s*1fr\)/)
  assert.match(rule('.breakpoint-target-suggestions > div > span'), /repeat\(auto-fit,\s*minmax\(136px,\s*1fr\)\)/)
  assert.doesNotMatch(rule('.breakpoint-target-suggestions > div > span'), /overflow-x:\s*auto/)
  assert.match(rule('::-webkit-scrollbar'), /width:\s*8px/)
  assert.match(rule('::-webkit-scrollbar-button'), /display:\s*none/)
})

test('keeps breakpoint evidence assistive and Session controls vertically contained', () => {
  assert.match(rule('.session-filters input'), /padding:\s*0 10px/)
  assert.match(rule('.session-filters input'), /line-height:\s*18px/)
  assert.match(rule('.session-filters select'), /padding:\s*0 32px 0 10px/)
  assert.match(rule('.session-filters select'), /line-height:\s*18px/)

  assert.match(app, /const breakpointReferenceInteractionId = ref\(null\)/)
  assert.match(app, /class="breakpoint-reference-evidence"/)
  assert.match(app, /class="breakpoint-reference-field-row"/)
  assert.match(app, /hitEvidenceRows\(snapshot\)/)
  assert.match(app, /期望值/)
  assert.match(app, /实际命中值/)
  assert.match(app, /精简条件证据，不是当前规则或完整 payload 副本/)
  assert.match(app, />据此新建断点</)
  assert.match(app, /newBreakpoint\(browsedInterface\)/)
  assert.match(app, /newBreakpoint\(browsedInteraction, browsedInteraction\.interaction_id\)/)
  assert.match(app, /conditionFromReferenceField\(field, breakpointReferenceSource\.value\)/)
  assert.match(app, /existingConditionIndex\(breakpointForm\.conditions, breakpointReferenceSource, field\.path\)/)
  assert.match(app, /function confirmBreakpointTargetChange\(object, command\)/)
  assert.match(app, /function chooseBreakpointObject\(object\)\s*\{[\s\S]*?confirmBreakpointTargetChange\(object, breakpointForm\.command\)/)
  assert.match(app, /function chooseBreakpointCommand\(command\)\s*\{[\s\S]*?confirmBreakpointTargetChange\(breakpointForm\.object, command\)/)
  assert.match(app, /function selectBreakpointReference\(item\)\s*\{[\s\S]*?confirmBreakpointTargetChange\(item\.object, item\.command\)/)
  assert.match(app, /function breakpointObjectEvidence\(item\)\s*\{[\s\S]*?formatTime\(item\.last_seen_at\)/)
  assert.match(app, /params 与 result 证据都只取自该调用/)
  assert.match(app, /breakpointConditionEvidenceStates\[conditionIndex\]\.warning/)
  assert.match(app, /仍可保存并启用/)
  assert.match(app, /仍可按当前文本提前配置并保存/)
  assert.match(app, /body:\s*\{[\s\S]*?name:\s*breakpointForm\.name,[\s\S]*?object:\s*breakpointForm\.object,[\s\S]*?command:\s*breakpointForm\.command,[\s\S]*?pause_point:\s*breakpointForm\.pause_point,[\s\S]*?conditions:\s*breakpointConditionDraft\.value\.conditions,[\s\S]*?\}/)
  assert.doesNotMatch(app, /body:\s*\{[\s\S]{0,400}(?:sample_ref|reference_interaction)/)

  assert.match(rule('.breakpoint-draft-workspace'), /display:\s*grid/)
  assert.match(styles, /@container \(min-width:\s*900px\)[\s\S]*?\.breakpoint-draft-workspace\s*\{[\s\S]*?grid-template-columns:/)
  assert.match(rule('.condition-row.evidence-highlight'), /border-color:\s*var\(--qt-primary\)/)
})
